name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Package with Maven
        run: mvn package
      - name: Run docker compose
        run: docker compose up --abort-on-container-exit
      - name: view logs
        run: docker logs devops3-app-1
      - name: Copy Output
        run: docker container cp devops3-app-1:./tmp/output ./
      - name: List dirs
        run: |
          pwd
          ls
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output # The branch the action should deploy to.
          folder: output # The folder we are copying
      # - name: Deploy2
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./output
      #     publish_branch: output
